### ISSUE TITLE
gtk-3 and conda

### ISSUE THREAD

**Issue by BTMeeks** [evainlau/pycao#1]
I'm trying to get started with picao on a Mac using Anaconda (mini conda). So far, I've done:

 ```
$ brew install poverty
$ conda install pygobject

$ conda list pygobject
# packages in environment at /Users/barton/miniconda3:
#
# Name                    Version                   Build  Channel
 pygobject                 3.30.4          py37h21bf938_1000    conda-forge

```
I made a copy of template.py as testPyco.py and execute "python testPyco.py", and I get:
```
(base) Bartons-MBP:pycao barton$ python testPyco.py 
Traceback (most recent call last):
  File "testPyco.py", line 86, in <module>
    camera.show # show the photo, ie calls povray. 
  File "/Users/barton/pycao/cameras.py", line 100, in show
    import viewer
  File "/Users/barton/pycao/viewer.py", line 14, in <module>
    gi.require_version('Gtk', '3.0')
  File "/Users/barton/miniconda3/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```
I'm guessing that the issue is Gtk 2 instead of 3, but I don't know what to do about it.

**Comment by evainlau** [comment]
Hello, you may simply replace the command camera.show 
by the command camera.show_without_viewer
Then gtk will not be necessary. 

You will keep all the functionalities but the possibility to move the camera interactivly. Use the last version to be sure that it works. The last version is the branch architecture library today. I will probably soon merge with the main branch. 

The documentation for the last branch is at : http://math.univ-angers.fr/~evain/software/pycao/documentation/index.html
